name: flutter_module_app
description: "A new Flutter module project."

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.flutter_module_app
    iosBundleIdentifier: com.example.flutterModuleApp
