name: flutter_module_app
description: "A new Flutter module project."

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.41.4

dependencies:
  flutter:
    sdk: flutter

dependency_overrides:
  flutter_test: 
    sdk: flutter
  
flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.flutter_module_app
    iosBundleIdentifier: com.example.flutterModuleApp
