name: flutter_module_app
description: "A new Flutter module project."

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: 2.24.2
  firebase_core_platform_interface: 5.0.0
  firebase_crashlytics: 3.4.9
  flutter_lints: ^2.0.0
  flutter_plugin_android_lifecycle: 2.0.8
  socket_io_client: 2.0.0
  logger: 1.1.0
  drift: 2.0.2+1
  sqlite3_flutter_libs: 0.5.0
  path_provider_android: 2.1.0
  path_provider_foundation: 2.3.2
  path: ^1.8.0
  easy_debounce: 2.0.3
  rxdart: 0.27.7
  dio: 5.2.0+1
  cached_network_image: 3.3.1
  dart_date: ^1.1.1
  go_router: 14.0.1
  image_picker: 0.8.6+3
  image_picker_android: 0.8.5+7
  intl: ^0.18.1
  fluttertoast: 8.0.9
  photo_view: 0.14.0
  shared_preferences: 2.0.8
  permission_handler: 10.2.0
  url_launcher: 6.2.6
  linkify: 5.0.0
  image_editor: 1.1.0
  dio_cache_interceptor_db_store: 5.0.0
  dio_cache_interceptor: 3.5.0
  flutter_riverpod: 2.3.6
  freezed_annotation: ^2.4.1
  lottie: 2.0.0
  scratcher: 2.5.0
  flutter_link_previewer: 3.2.2
  collection: ^1.18.0

  
flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.flutter_module_app
    iosBundleIdentifier: com.example.flutterModuleApp
